#!/bin/bash
APPEND_PATHS=(
	"$XDG_DATA_HOME/bin"
	"$XDG_DATA_HOME/cabal/bin"
  "$HOME/.local/bin"
)

PREPEND_PATHS=(
	"$XDG_DATA_HOME/cargo/bin"
	"$XDG_DATA_HOME/pnpm"
)

for loc in "${APPEND_PATHS[@]}"
do
	case ":$PATH:" in
		*:"$loc":*)
			;;
		*)
			export PATH="$PATH:$loc"
			;;
	esac
done

for loc in "${PREPEND_PATHS[@]}" 
do
	case ":$PATH:" in
		*:"$loc":*)
			;;
		*)
			export PATH="$loc:$PATH"
			;;
	esac
done
