#!/bin/sh


if [ -z "$1" ]
then
	sudo cp /home/ellie/.local/manual/OpenAsar/app.asar /usr/lib64/discord/resources/app.asar
	echo "app.asar updated!"
else
	cp $1 /home/ellie/.local/manual/OpenAsar/app.asar
	/home/ellie/.local/manual/OpenAsar/update.sh
fi
