return {
  settings = {
    tailwindCSS = {
      experimental = {
        classRegex = {
          "clsx[`]([\\s\\S][^`]*)[`]",
          { "clsx\\(([^]*)\\)", "(?:'|\"|`)([^\"'`]*)(?:'|\"|`)" },
        },
      },
    },
  },

  init_options = {
    userLanguages = {
      rust = "html",
    },
  },

  filetypes = {
    "aspnetcorerazor",
    "astro",
    "astro-markdown",
    "blade",
    "clojure",
    "css",
    "django-html",
    "edge",
    "eelixir",
    "ejs",
    "elixir",
    "erb",
    "eruby",
    "gohtml",
    "gohtmltmpl",
    "haml",
    "handlebars",
    "hbs",
    "heex",
    "html",
    "html-eex",
    "htmldjango",
    "jade",
    "javascript",
    "javascriptreact",
    "leaf",
    "less",
    "liquid",
    "markdown",
    "mdx",
    "mustache",
    "njk",
    "nunjucks",
    "php",
    "postcss",
    "razor",
    "reason",
    "rescript",
    "rust",
    "sass",
    "scss",
    "slim",
    "stylus",
    "sugarss",
    "svelte",
    "twig",
    "typescript",
    "typescriptreact",
    "vue",
  },
}
