local function config()
  vim.g.symbols_outline = {
    highlight_hovered_item = true,
    show_guides = true,
    auto_preview = false,
    position = "right",
    relative_width = true,
    width = 20,
    auto_close = false,
    show_numbers = false,
    show_relative_numbers = false,
    show_symbol_details = true,
    preview_bg_highlight = "Pmenu",
    keymaps = { -- These keymaps can be a string or a table for multiple keys
      close = { "<Esc>", "q" },
      goto_location = "<Cr>",
      focus_location = "o",
      hover_symbol = "<C-space>",
      toggle_preview = "K",
      rename_symbol = "r",
      code_actions = "a",
    },
    lsp_blacklist = {},
    symbol_blacklist = {},
    symbols = {
      File = { icon = symbols.File, hl = "TSURI" },
      Module = { icon = symbols.Module, hl = "TSNamespace" },
      Namespace = { icon = symbols.Namespace, hl = "TSNamespace" },
      Package = { icon = symbols.Package, hl = "TSNamespace" },
      Class = { icon = symbols.Class, hl = "TSType" },
      Method = { icon = symbols.Method, hl = "TSMethod" },
      Property = { icon = symbols.Property, hl = "TSMethod" },
      Field = { icon = symbols.Field, hl = "TSField" },
      Constructor = { icon = symbols.Constructor, hl = "TSConstructor" },
      Enum = { icon = symbols.Enum, hl = "TSType" },
      Interface = { icon = symbols.Interface, hl = "TSType" },
      Function = { icon = symbols.Function, hl = "TSFunction" },
      Variable = { icon = symbols.Variable, hl = "TSConstant" },
      Constant = { icon = symbols.Constant, hl = "TSConstant" },
      String = { icon = symbols.String, hl = "TSString" },
      Number = { icon = symbols.Number, hl = "TSNumber" },
      Boolean = { icon = symbols.Boolean, hl = "TSBoolean" },
      Array = { icon = symbols.Array, hl = "TSConstant" },
      Object = { icon = symbols.Object, hl = "TSType" },
      Key = { icon = symbols.Key, hl = "TSType" },
      Null = { icon = symbols.Null, hl = "TSType" },
      EnumMember = { icon = symbols.EnumMember, hl = "TSField" },
      Struct = { icon = symbols.Struct, hl = "TSType" },
      Event = { icon = symbols.Event, hl = "TSType" },
      Operator = { icon = symbols.Operator, hl = "TSOperator" },
      TypeParameter = { icon = symbols.TypeParameter, hl = "TSParameter" },
    },
  }

  require("which-key").register({ ["<leader>o"] = { ":SymbolsOutline<CR>", "Toggle outline" } })
end

return { "simrat39/symbols-outline.nvim", config = config, requires = "folke/which-key.nvim" }
