# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.21.2" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.21.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.21.2.tgz";
        sha512 = "URpaIJQwEkEC2T9Kn+Ai6Xe/02iNaVCuT/PtoRz3GPVJVDpPd7mLo+VddTbhCRU9TXqW5mSrQfXZyi8kDKOVpQ==";
      };
    };
    "@emmetio/abbreviation-2.2.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.2.3.tgz";
        sha512 = "87pltuCPt99aL+y9xS6GPZ+Wmmyhll2WXH73gG/xpGcQ84DRnptBsI2r0BeIQ0EB/SQTOe2ANPqFqj3Rj5FOGA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.4" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.4.tgz";
        sha512 = "qk9L60Y+uRtM5CPbB0y+QNl/1XKE09mSO+AhhSauIfr2YOx/ta3NJw2d8RtCFxgzHeRqFRr8jgyzThbu+MZ4Uw==";
      };
    };
    "@emmetio/scanner-1.0.0" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.0.tgz";
        sha512 = "8HqW8EVqjnCmWXVpqAOZf+EGESdkR27odcMMMGefgKXtar00SoYNSryGv//TELI4T3QFsECo78p+0lmalk/CFA==";
      };
    };
    "@johnsoncodehk/pug-beautify-0.2.2" = {
      name = "_at_johnsoncodehk_slash_pug-beautify";
      packageName = "@johnsoncodehk/pug-beautify";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@johnsoncodehk/pug-beautify/-/pug-beautify-0.2.2.tgz";
        sha512 = "qqNS/YD0Nck5wtQLCPHAfGVgWbbGafxSPjNh0ekYPFSNNqnDH2kamnduzYly8IiADmeVx/MfAE1njMEjVeHTMA==";
      };
    };
    "@volar-plugins/css-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_css";
      packageName = "@volar-plugins/css";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/css/-/css-2.0.0-alpha.13.tgz";
        sha512 = "Oca+JJAp/uFLi9WHYLekEytpMgMZPN28pwd80SzWC/r5r/GqfH9eCvdEa4GddeIiLZKZYLwxP6Tz+mzK7YfacA==";
      };
    };
    "@volar-plugins/emmet-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_emmet";
      packageName = "@volar-plugins/emmet";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/emmet/-/emmet-2.0.0-alpha.13.tgz";
        sha512 = "AFE7arG0wi3wbqPfSO/wjw2xF/1qQgHEMrS7i2kmAYQK+Vwzevgc4XTH1XGmcss6aUOFIantkVg3Q4wvorLbvg==";
      };
    };
    "@volar-plugins/html-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_html";
      packageName = "@volar-plugins/html";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/html/-/html-2.0.0-alpha.13.tgz";
        sha512 = "z9ogEvMtrqkSl/m5h9019mWPbA2R8jua+AXkVJhLGIt/pc+S9SmMGpX+8eZGCPQhNkvzeoR9Cfg1wP0k/tGDVA==";
      };
    };
    "@volar-plugins/json-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_json";
      packageName = "@volar-plugins/json";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/json/-/json-2.0.0-alpha.13.tgz";
        sha512 = "DaP+BOpfuJu5mRGaX+8csFLcGdq8OldNT/WpjM8jpsA+Bi3BuFctkMc3Pz7f14dwv8H15KpDub9D7ErnwpeGuQ==";
      };
    };
    "@volar-plugins/pug-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_pug";
      packageName = "@volar-plugins/pug";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/pug/-/pug-2.0.0-alpha.13.tgz";
        sha512 = "chlweqIZHOsbrZsLWrrUUTYvd3nAV7ItzkglWV8WmHwzXJmTr3r+jDgRik1YwYOGQgRFTi4jDuawAByuzqgETg==";
      };
    };
    "@volar-plugins/pug-beautify-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_pug-beautify";
      packageName = "@volar-plugins/pug-beautify";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/pug-beautify/-/pug-beautify-2.0.0-alpha.13.tgz";
        sha512 = "EnwHRI+TX6QqO51sOZ7bpKyn6zl5QZ1PTC+H2iYVZNFPxPwR4XT0n0H+Qp8FoXq6SRb3i5bPLZBHH071YuZBgQ==";
      };
    };
    "@volar-plugins/typescript-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_typescript";
      packageName = "@volar-plugins/typescript";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/typescript/-/typescript-2.0.0-alpha.13.tgz";
        sha512 = "2Tj2SzLKzfkyZ4sHgPTYFZ1DS/ZXsvPuGTth4kmPX450wbApPD5vI7UWSCv/VtkUbrMhmJ9CFUeZq8QHBlPQkw==";
      };
    };
    "@volar-plugins/typescript-twoslash-queries-2.0.0-alpha.13" = {
      name = "_at_volar-plugins_slash_typescript-twoslash-queries";
      packageName = "@volar-plugins/typescript-twoslash-queries";
      version = "2.0.0-alpha.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar-plugins/typescript-twoslash-queries/-/typescript-twoslash-queries-2.0.0-alpha.13.tgz";
        sha512 = "6UnRCIUAyW6M4Yxfi8hF5dG2oLeOOliYvavZezaxSxma1X0RLeJgQBDJDZEoPJl4EgEbEkiFoNtUWPE2jxHi4Q==";
      };
    };
    "@volar/language-core-1.0.24" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "1.0.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-1.0.24.tgz";
        sha512 = "vTN+alJiWwK0Pax6POqrmevbtFW2dXhjwWiW/MW4f48eDYPLdyURWcr8TixO7EN/nHsUBj2udT7igFKPtjyAKg==";
      };
    };
    "@volar/language-core-1.3.0-alpha.0" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "1.3.0-alpha.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-1.3.0-alpha.0.tgz";
        sha512 = "W3uMzecHPcbwddPu4SJpUcPakRBK/y/BP+U0U6NiPpUX1tONLC4yCawt+QBJqtgJ+sfD6ztf5PyvPL3hQRqfOA==";
      };
    };
    "@volar/language-server-1.3.0-alpha.0" = {
      name = "_at_volar_slash_language-server";
      packageName = "@volar/language-server";
      version = "1.3.0-alpha.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-server/-/language-server-1.3.0-alpha.0.tgz";
        sha512 = "pEpg0Mc74CDD0pIBs6qx632n9OGV1UGq3GFhX8anCiflSBb3nRa1Ry1ImkwIpCNaZPSnx3Mv7zDxYK+e7XNCfA==";
      };
    };
    "@volar/language-service-1.0.24" = {
      name = "_at_volar_slash_language-service";
      packageName = "@volar/language-service";
      version = "1.0.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-service/-/language-service-1.0.24.tgz";
        sha512 = "Y37lzNRVM2xDY1kFXn88n9nkXUD1H0ZffXXLbsFbkUhMM1pKBgcJGEuRXoATXu62R0NmrcGXrktjTPQ4VjKQuA==";
      };
    };
    "@volar/language-service-1.3.0-alpha.0" = {
      name = "_at_volar_slash_language-service";
      packageName = "@volar/language-service";
      version = "1.3.0-alpha.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-service/-/language-service-1.3.0-alpha.0.tgz";
        sha512 = "dEzslTv2bHNP+ariZu0kj1C7ClSMzfX41Cmctp2MnNMN68F/olrmP4sT84+D7COeYj+wz7SduDqWSsWPGXfT2g==";
      };
    };
    "@volar/shared-1.0.24" = {
      name = "_at_volar_slash_shared";
      packageName = "@volar/shared";
      version = "1.0.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/shared/-/shared-1.0.24.tgz";
        sha512 = "30mqmNsw49xlGhziL59z6kP6/TlBatkeOzMImUSWmn1QtqV7r2onDGgNNdCqSa1esTo4UtGup6yqqM2oUwrMSQ==";
      };
    };
    "@volar/shared-1.3.0-alpha.0" = {
      name = "_at_volar_slash_shared";
      packageName = "@volar/shared";
      version = "1.3.0-alpha.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/shared/-/shared-1.3.0-alpha.0.tgz";
        sha512 = "+sRJ8tHp9IHpD3X2caeDRLA1BU7ntxRh8kpjhML9xUHYfGJv+C8pQUYqfAjemPwU4Z8F3C4gEM1Cvzg6aoyyLw==";
      };
    };
    "@volar/source-map-1.0.24" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "1.0.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-1.0.24.tgz";
        sha512 = "Qsv/tkplx18pgBr8lKAbM1vcDqgkGKQzbChg6NW+v0CZc3G7FLmK+WrqEPzKlN7Cwdc6XVL559Nod8WKAfKr4A==";
      };
    };
    "@volar/source-map-1.3.0-alpha.0" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "1.3.0-alpha.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-1.3.0-alpha.0.tgz";
        sha512 = "jSdizxWFvDTvkPYZnO6ew3sBZUnS0abKCbuopkc0JrIlFbznWC/fPH3iPFIMS8/IIkRxq1Jh9VVG60SmtsdaMQ==";
      };
    };
    "@volar/typescript-faster-1.0.24" = {
      name = "_at_volar_slash_typescript-faster";
      packageName = "@volar/typescript-faster";
      version = "1.0.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript-faster/-/typescript-faster-1.0.24.tgz";
        sha512 = "8JtPkR3p2EVpBrD5puuP4y4CA7LVIkMV/+O2a/biD5zHyfqwN+s5j1/perp0D/5RgyxLJWhWIIYo1HR5ac5jlA==";
      };
    };
    "@volar/typescript-faster-1.3.0-alpha.0" = {
      name = "_at_volar_slash_typescript-faster";
      packageName = "@volar/typescript-faster";
      version = "1.3.0-alpha.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript-faster/-/typescript-faster-1.3.0-alpha.0.tgz";
        sha512 = "9qQHzjARrwrx7HElzOAU8B0QL66HuVjRHNVaOAcoraRk+8ioGDVRaHPS4vuE+cnXXieul28UeAk7AQl/o639Ww==";
      };
    };
    "@volar/vue-language-core-1.2.0" = {
      name = "_at_volar_slash_vue-language-core";
      packageName = "@volar/vue-language-core";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-language-core/-/vue-language-core-1.2.0.tgz";
        sha512 = "w7yEiaITh2WzKe6u8ZdeLKCUz43wdmY/OqAmsB/PGDvvhTcVhCJ6f0W/RprZL1IhqH8wALoWiwEh/Wer7ZviMQ==";
      };
    };
    "@volar/vue-language-service-1.2.0" = {
      name = "_at_volar_slash_vue-language-service";
      packageName = "@volar/vue-language-service";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-language-service/-/vue-language-service-1.2.0.tgz";
        sha512 = "VCD9PN3IhdU0TLnuu7X3b0qkFMCqd5NKgKblQ77W3bCWLbRAiy+wR6tknB2CjPU3iAX1Iilgoa55CTu52Snnkg==";
      };
    };
    "@vscode/emmet-helper-2.8.6" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.8.6.tgz";
        sha512 = "IIB8jbiKy37zN8bAIHx59YmnIelY78CGHtThnibD/d3tQOKRY83bYVi9blwmZVUZh6l9nfkYH3tvReaiNxY9EQ==";
      };
    };
    "@vscode/l10n-0.0.11" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.11.tgz";
        sha512 = "ukOMWnCg1tCvT7WnDfsUKQOFDQGsyR5tNgRpwmqi+5/vzU3ghdDXzvIM4IOPdSb3OeSsBNvmSL8nxIVOqi2WXA==";
      };
    };
    "@vue/compiler-core-3.2.47" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.2.47.tgz";
        sha512 = "p4D7FDnQb7+YJmO2iPEv0SQNeNzcbHdGByJDsT4lynf63AFkOTFN07HsiRSvjGo0QrxR/o3d0hUyNCUnBU2Tig==";
      };
    };
    "@vue/compiler-dom-3.2.47" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.2.47.tgz";
        sha512 = "dBBnEHEPoftUiS03a4ggEig74J2YBZ2UIeyfpcRM2tavgMWo4bsEfgCGsu+uJIL/vax9S+JztH8NmQerUo7shQ==";
      };
    };
    "@vue/compiler-sfc-3.2.47" = {
      name = "_at_vue_slash_compiler-sfc";
      packageName = "@vue/compiler-sfc";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-sfc/-/compiler-sfc-3.2.47.tgz";
        sha512 = "rog05W+2IFfxjMcFw10tM9+f7i/+FFpZJJ5XHX72NP9eC2uRD+42M3pYcQqDXVYoj74kHMSEdQ/WmCjt8JFksQ==";
      };
    };
    "@vue/compiler-ssr-3.2.47" = {
      name = "_at_vue_slash_compiler-ssr";
      packageName = "@vue/compiler-ssr";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-ssr/-/compiler-ssr-3.2.47.tgz";
        sha512 = "wVXC+gszhulcMD8wpxMsqSOpvDZ6xKXSVWkf50Guf/S+28hTAXPDYRTbLQ3EDkOP5Xz/+SY37YiwDquKbJOgZw==";
      };
    };
    "@vue/reactivity-3.2.47" = {
      name = "_at_vue_slash_reactivity";
      packageName = "@vue/reactivity";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.2.47.tgz";
        sha512 = "7khqQ/75oyyg+N/e+iwV6lpy1f5wq759NdlS1fpAhFXa8VeAIKGgk2E/C4VF59lx5b+Ezs5fpp/5WsRYXQiKxQ==";
      };
    };
    "@vue/reactivity-transform-3.2.47" = {
      name = "_at_vue_slash_reactivity-transform";
      packageName = "@vue/reactivity-transform";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity-transform/-/reactivity-transform-3.2.47.tgz";
        sha512 = "m8lGXw8rdnPVVIdIFhf0LeQ/ixyHkH5plYuS83yop5n7ggVJU+z5v0zecwEnX7fa7HNLBhh2qngJJkxpwEEmYA==";
      };
    };
    "@vue/shared-3.2.47" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.2.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.2.47.tgz";
        sha512 = "BHGyyGN3Q97EZx0taMQ+OLNuZcW3d37ZEVmEAyeoA9ERdGvm9Irc/0Fua8SNyOtV1w6BS4q25wbMzJujO9HIfQ==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "de-indent-1.0.2" = {
      name = "de-indent";
      packageName = "de-indent";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/de-indent/-/de-indent-1.0.2.tgz";
        sha512 = "e/1zu3xH5MQryN2zdVaF0OrdNLUbvWxzMbi+iNA6Bky7l1RoP8a2fIbRocyHclXt/arDrrR6lL3TqFD9pMQTsg==";
      };
    };
    "emmet-2.3.6" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.3.6.tgz";
        sha512 = "pLS4PBPDdxuUAmw7Me7+TcHbykTsBKN/S9XJbUOMFQrNv9MoshzyMFK/R57JBm94/6HSL4vHnDeEmxlC82NQ4A==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-intrinsic-1.2.0" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.0.tgz";
        sha512 = "L049y6nFOuom5wGyRc3/gdTLO94dySVKRACj1RmJZBQXlbTMhtNIgkWkUHq+jYmZvKf14EW1EoJnnjbmoHij0Q==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jsonc-parser-3.2.0" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.2.0.tgz";
        sha512 = "gfFQZrcTc8CnKXp6Y4/CBT3fTc0OVuDofpre4aEeEpSBPV5X5v4+Vmx+8snU7RLPrNHPKSgLxGo9YuQzz20o+w==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "magic-string-0.25.9" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.25.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.25.9.tgz";
        sha512 = "RmF0AsMzgt25qzqqLc1+MbHmhdx0ojF2Fvs4XnOqz2ZOBXzzkEwc/dJQZCYHAn7v1jbVOjAZfK8msRn4BxO4VQ==";
      };
    };
    "minimatch-6.2.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-6.2.0.tgz";
        sha512 = "sauLxniAmvnhhRjFwPNnJKaPFYyddAgbYdeUpHULtCT/GhzdCx/MDNy+Y40lBxTQUrMzDE8e0S43Z5uqfO0REg==";
      };
    };
    "muggle-string-0.1.0" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.1.0.tgz";
        sha512 = "Tr1knR3d2mKvvWthlk7202rywKbiOm4rVFLsfAaSIhJ6dt9o47W4S+JMtWhd/PW9Wrdew2/S2fSvhz3E2gkfEg==";
      };
    };
    "muggle-string-0.2.2" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.2.2.tgz";
        sha512 = "YVE1mIJ4VpUMqZObFndk9CJu6DBJR/GB13p3tXuNbwD4XExaI5EOuRl6BHeIDxIqXZVxSfAC+y6U1Z/IxCfKUg==";
      };
    };
    "nanoid-3.3.4" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.4.tgz";
        sha512 = "MqBkQh/OHTS2egovRtLk45wEyNXwF+cokD+1YPf9u5VfJiRdAiRwB2froX5Co9Rh20xs4siNPm8naNotSD6RBw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "postcss-8.4.21" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.21.tgz";
        sha512 = "tP7u/Sn/dVxK2NnruI4H9BG+x+Wxz6oeZ1cJ8P6G/PZY0IKk4k/63TDsQf2kQq3+qoJeLm2kIBUNlZe3zgb4Zg==";
      };
    };
    "prettier-2.8.4" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.8.4.tgz";
        sha512 = "vIS4Rlc2FNh0BySk3Wkd6xmwxB0FpOndW5fisM5H8hsZSxU2VWVB5CWIkIjWvrHjIhxk2g3bfMKM87zNTrZddw==";
      };
    };
    "pug-error-2.0.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.0.0.tgz";
        sha512 = "sjiUsi9M4RAGHktC1drQfCr5C5eriu24Lfbt4s+7SykztEOwVZtbFk1RRq0tzLxcMxMYTBR+zMQaG07J/btayQ==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "request-light-0.7.0" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.7.0.tgz";
        sha512 = "lMbBMrDoxgsyO+yB3sDcrDuX85yYt7sS8BfQd11jtbW/z5ZWgLZRcEGLsLoYw7I0WSUGQBs8CC8ScIxkTX1+6Q==";
      };
    };
    "semver-7.3.8" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.8.tgz";
        sha512 = "NB1ctGL5rlHrPJtFDVIVzTyQylMLu9N9VICA6HSFJo8MCGVTMW6gfpicwKmmK/dAjTOrqu5l63JJOpDSrAis3A==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "svelte-3.56.0" = {
      name = "svelte";
      packageName = "svelte";
      version = "3.56.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-3.56.0.tgz";
        sha512 = "LvXiJbjdvJKwB/0CQyYpDX0q+hFqCyWmybzC2G6eK1tJJA/RSRCytTfNmjHv+RHlLuA70vWG7nXp6gbeErYvRA==";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha512 = "VSsyNPPW74RpHwR8Fc21uubwHY7wMDeJLys2IX5zJNih+OnAnaifKHo+1LHT7DAdloQ7apeaaWg8l7qnf/TnEg==";
      };
    };
    "typesafe-path-0.2.2" = {
      name = "typesafe-path";
      packageName = "typesafe-path";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typesafe-path/-/typesafe-path-0.2.2.tgz";
        sha512 = "OJabfkAg1WLZSqJAJ0Z6Sdt3utnbzr/jh+NAHoyWHJe8CMSy79Gm085094M9nvTPy22KzTVn5Zq5mbapCI/hPA==";
      };
    };
    "typescript-4.9.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz";
        sha512 = "1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==";
      };
    };
    "vscode-css-languageservice-6.2.4" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.2.4.tgz";
        sha512 = "9UG0s3Ss8rbaaPZL1AkGzdjrGY8F+P+Ne9snsrvD9gxltDGhsn8C2dQpqQewHrMW37OvlqJoI8sUU2AWDb+qNw==";
      };
    };
    "vscode-html-languageservice-5.0.4" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.0.4.tgz";
        sha512 = "tvrySfpglu4B2rQgWGVO/IL+skvU7kBkQotRlxA7ocSyRXOZUd6GA13XHkxo8LPe07KWjeoBlN1aVGqdfTK4xA==";
      };
    };
    "vscode-json-languageservice-5.3.2" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.3.2.tgz";
        sha512 = "5td6olfoNdtyxnNA4uocq7V9jdTJt63o9mGEntQb6cbD2HiObZW2XgbSj6nRaebWwBCiYdWpFklNjm6Wz6Xy1Q==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-textdocument-1.0.9" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.9.tgz";
        sha512 = "NPfHVGFW2/fQEWHspr8x3PXhRgtFbuDZdl7p6ifuN3M7nk2Yjf5POr/NfDBuAiQG88DehDyJ7nGOT+p+edEtbw==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-nls-5.2.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz";
        sha512 = "RAaHx7B14ZU04EU31pT+rKz2/zSl7xMsfIZuo8pd+KZO6PXtQmpevpq3vxvWNcrGbdmhM/rr5Uw5Mz+NBfhVng==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
    "vscode-uri-3.0.7" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.7.tgz";
        sha512 = "eOpPHogvorZRobNqJGhapa0JdwaxpjVvyBp0QIUMRMSf8ZAlqOdEquKuRmw9Qwu0qXtJIWqFtMkmvJjUZmMjVA==";
      };
    };
    "vue-component-meta-1.2.0" = {
      name = "vue-component-meta";
      packageName = "vue-component-meta";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-component-meta/-/vue-component-meta-1.2.0.tgz";
        sha512 = "z+/pL4txu5qCULbGHFn6vOlSR1V5gFDGWkD64Z2yLlKtYr0Wlb9oOfWTaXxpSl7R+EiX7JusbTlek0szSYeH1g==";
      };
    };
    "vue-template-compiler-2.7.14" = {
      name = "vue-template-compiler";
      packageName = "vue-template-compiler";
      version = "2.7.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-template-compiler/-/vue-template-compiler-2.7.14.tgz";
        sha512 = "zyA5Y3ArvVG0NacJDkkzJuPQDF8RFeRlzV2vLeSnhSpieO6LK2OVbdLPi5MPPs09Ii+gMO8nY4S3iKQxBxDmWQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  "@volar/vue-language-server" = nodeEnv.buildNodePackage {
    name = "_at_volar_slash_vue-language-server";
    packageName = "@volar/vue-language-server";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@volar/vue-language-server/-/vue-language-server-1.2.0.tgz";
      sha512 = "W2ADSarZp1BSvGrNEN5NnvieKnJuR0NAZqBJVX6enDsyYPKa+I5HImjUbHGAIszk3XPR/SZc3CmRCROxS0Tw2A==";
    };
    dependencies = [
      sources."@babel/parser-7.21.2"
      sources."@emmetio/abbreviation-2.2.3"
      sources."@emmetio/css-abbreviation-2.1.4"
      sources."@emmetio/scanner-1.0.0"
      sources."@johnsoncodehk/pug-beautify-0.2.2"
      (sources."@volar-plugins/css-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      (sources."@volar-plugins/emmet-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      (sources."@volar-plugins/html-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      (sources."@volar-plugins/json-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      sources."@volar-plugins/pug-2.0.0-alpha.13"
      (sources."@volar-plugins/pug-beautify-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      (sources."@volar-plugins/typescript-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      (sources."@volar-plugins/typescript-twoslash-queries-2.0.0-alpha.13" // {
        dependencies = [
          sources."@volar/language-core-1.0.24"
          sources."@volar/language-service-1.0.24"
          sources."@volar/shared-1.0.24"
          sources."@volar/source-map-1.0.24"
          sources."@volar/typescript-faster-1.0.24"
          sources."muggle-string-0.1.0"
        ];
      })
      sources."@volar/language-core-1.3.0-alpha.0"
      sources."@volar/language-server-1.3.0-alpha.0"
      sources."@volar/language-service-1.3.0-alpha.0"
      sources."@volar/shared-1.3.0-alpha.0"
      sources."@volar/source-map-1.3.0-alpha.0"
      sources."@volar/typescript-faster-1.3.0-alpha.0"
      sources."@volar/vue-language-core-1.2.0"
      sources."@volar/vue-language-service-1.2.0"
      (sources."@vscode/emmet-helper-2.8.6" // {
        dependencies = [
          sources."jsonc-parser-2.3.1"
          sources."vscode-uri-2.1.2"
        ];
      })
      sources."@vscode/l10n-0.0.11"
      sources."@vue/compiler-core-3.2.47"
      sources."@vue/compiler-dom-3.2.47"
      sources."@vue/compiler-sfc-3.2.47"
      sources."@vue/compiler-ssr-3.2.47"
      sources."@vue/reactivity-3.2.47"
      sources."@vue/reactivity-transform-3.2.47"
      sources."@vue/shared-3.2.47"
      sources."acorn-7.4.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-2.0.1"
      sources."call-bind-1.0.2"
      sources."character-parser-2.2.0"
      sources."de-indent-1.0.2"
      sources."emmet-2.3.6"
      sources."estree-walker-2.0.2"
      sources."function-bind-1.1.1"
      sources."get-intrinsic-1.2.0"
      sources."has-1.0.3"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.0"
      sources."he-1.2.0"
      sources."is-expression-4.0.0"
      sources."is-regex-1.1.4"
      sources."jsonc-parser-3.2.0"
      sources."lru-cache-6.0.0"
      sources."magic-string-0.25.9"
      sources."minimatch-6.2.0"
      sources."muggle-string-0.2.2"
      sources."nanoid-3.3.4"
      sources."object-assign-4.1.1"
      sources."picocolors-1.0.0"
      sources."postcss-8.4.21"
      sources."pug-error-2.0.0"
      sources."pug-lexer-5.0.1"
      sources."pug-parser-6.0.0"
      sources."request-light-0.7.0"
      sources."semver-7.3.8"
      sources."source-map-0.6.1"
      sources."source-map-js-1.0.2"
      sources."sourcemap-codec-1.4.8"
      sources."token-stream-1.0.0"
      sources."typesafe-path-0.2.2"
      sources."typescript-4.9.5"
      sources."vscode-css-languageservice-6.2.4"
      sources."vscode-html-languageservice-5.0.4"
      sources."vscode-json-languageservice-5.3.2"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.9"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.0.7"
      sources."vue-component-meta-1.2.0"
      sources."vue-template-compiler-2.7.14"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://github.com/johnsoncodehk/volar#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-svelte = nodeEnv.buildNodePackage {
    name = "prettier-plugin-svelte";
    packageName = "prettier-plugin-svelte";
    version = "2.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-2.9.0.tgz";
      sha512 = "3doBi5NO4IVgaNPtwewvrgPpqAcvNv0NwJNflr76PIGgi9nf1oguQV1Hpdm9TI2ALIQVn/9iIwLpBO5UcD2Jiw==";
    };
    dependencies = [
      sources."prettier-2.8.4"
      sources."svelte-3.56.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Svelte plugin for prettier";
      homepage = "https://github.com/sveltejs/prettier-plugin-svelte#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
